---
apiVersion: v1
kind: Service
metadata:
  name: simple-service-lb
spec:
  selector:
    app: simple-service
  ports:
    - protocol: TCP
      port: 8989
      nodePort: 30880
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-service
spec:
  selector:
    matchLabels:
      app: simple-service
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-service
    spec:
      containers:
        - name: simple-service
          image: simple-service:v1.0.0
          imagePullPolicy: Never
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: APP_PORT
              value: "8989"
          ports:
            - name: grpc
              containerPort: 8989
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
            requests:
              memory: 256Mi
              cpu: 500m
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-service-ingress
spec:
  rules:
    - host: coder.192.168.10.0.xip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: coder-service
              servicePort: 8989
